from typing import Optional, List, Tuple

class Tensor:
    def abs(self, name: Optional[str] = None) -> Tensor: ...
    def acos(self, name: Optional[str] = None) -> Tensor: ...
    def acosh(self, name: Optional[str] = None) -> Tensor: ...
    def add(self, y: Tensor, name: Optional[str] = None) -> Tensor: ...
    def add_(self, y: Tensor, name: Optional[str] = None) -> None: ...
    def add_n(self, name: Optional[str] = None) -> Tensor: ...
    def addmm(self, x, y, beta=1.0, alpha=1.0, name: Optional[str] = None) -> Tensor: ...
    def all(self, axis: Optional[int] = None, keepdim: bool = False, name: Optional[str] = None) -> Tensor: ...
    def allclose(self, y: Tensor, rtol=1e-05, atol=1e-08, equal_nan=False, name: Optional[str] = None) -> Tensor: ...
    def amax(self, axis: Optional[int] = None, keepdim: bool = False, name: Optional[str] = None) -> Tensor: ...
    def amin(self, axis: Optional[int] = None, keepdim: bool = False, name: Optional[str] = None) -> Tensor: ...
    def angle(self, name: Optional[str] = None) -> Tensor: ...
    def any(self, axis: Optional[int] = None, keepdim: bool = False, name: Optional[str] = None) -> Tensor: ...
    def argmax(self, axis: Optional[int] = None, keepdim: bool = False, dtype='int64', name: Optional[str] = None) -> Tensor: ...
    def argmin(self, axis: Optional[int] = None, keepdim: bool = False, dtype='int64', name: Optional[str] = None) -> Tensor: ...
    def argsort(self, axis: int = -1, descending=False, name: Optional[str] = None) -> Tuple[Tensor, Tensor]: ...
    def as_complex(self, name: Optional[str] = None) -> Tensor: ...
    def as_real(self, name: Optional[str] = None) -> Tensor: ...
    def asin(self, name: Optional[str] = None) -> Tensor: ...
    def asinh(self, name: Optional[str] = None) -> Tensor: ...
    def astype(self, dtype) -> Tuple[]: ...
    def atan(self, name: Optional[str] = None) -> Tensor: ...
    def atanh(self, name: Optional[str] = None) -> Tensor: ...
    def backward(self, grad_tensor=None, retain_graph=False) -> Tuple[]: ...
    def bincount(self, weights=None, minlength=0, name: Optional[str] = None) -> Tensor: ...
    def bitwise_and(self, y: Tensor, out=None, name: Optional[str] = None) -> Tensor: ...
    def bitwise_not(self, out=None, name: Optional[str] = None) -> Tensor: ...
    def bitwise_or(self, y: Tensor, out=None, name: Optional[str] = None) -> Tensor: ...
    def bitwise_xor(self, y: Tensor, out=None, name: Optional[str] = None) -> Tensor: ...
    def bmm(self, y: Tensor, name: Optional[str] = None) -> Tensor: ...
    def broadcast_shape(self, y_shape) -> Tuple[]: ...
    def broadcast_tensors(self, name: Optional[str] = None) -> List[Tensor]: ...
    def broadcast_to(self, shape, name: Optional[str] = None) -> Tuple[]: ...
    def cast(self, dtype) -> Tensor: ...
    def ceil(self, name: Optional[str] = None) -> Tensor: ...
    def ceil_(self, name: Optional[str] = None) -> None: ...
    def cholesky(self, upper=False, name: Optional[str] = None) -> Tensor: ...
    def cholesky_solve(self, y: Tensor, upper=False, name: Optional[str] = None) -> Tensor: ...
    def chunk(self, chunks, axis: int = 0, name: Optional[str] = None) -> Tuple[]: ...
    def clear_grad(self) -> Tuple[]: ...
    def clip(self, min=None, max=None, name: Optional[str] = None) -> Tensor: ...
    def clip_(self, min=None, max=None, name: Optional[str] = None) -> None: ...
    def concat(self, axis: int = 0, name: Optional[str] = None) -> Tensor: ...
    def cond(self, p=None, name: Optional[str] = None) -> Tuple[]: ...
    def conj(self, name: Optional[str] = None) -> Tensor: ...
    def cos(self, name: Optional[str] = None) -> Tensor: ...
    def cosh(self, name: Optional[str] = None) -> Tensor: ...
    def cov(self, rowvar=True, ddof=True, fweights=None, aweights=None, name: Optional[str] = None) -> Tuple[]: ...
    def cross(self, y: Tensor, axis: int = 9, name: Optional[str] = None) -> Tensor: ...
    def cumprod(self, dim=None, dtype=None, name: Optional[str] = None) -> Tensor: ...
    def cumsum(self, axis: Optional[int] = None, dtype=None, name: Optional[str] = None) -> Tensor: ...
    def deg2rad(self, name: Optional[str] = None) -> Tuple[]: ...
    def diagonal(self, offset=0, axis1=0, axis2=1, name: Optional[str] = None) -> Tensor: ...
    def diff(self, n=1, axis: int = -1, prepend=None, append=None, name: Optional[str] = None) -> Tuple[]: ...
    def digamma(self, name: Optional[str] = None) -> Tensor: ...
    def dim(self) -> Tuple[]: ...
    def dist(self, y: Tensor, p=2, name: Optional[str] = None) -> Tensor: ...
    def divide(self, y: Tensor, name: Optional[str] = None) -> Tensor: ...
    def dot(self, y: Tensor, name: Optional[str] = None) -> Tensor: ...
    def eig(self, name: Optional[str] = None) -> Tuple[Tensor, Tensor]: ...
    def eigvals(self, name: Optional[str] = None) -> Tensor: ...
    def eigvalsh(self, UPLO='L', name: Optional[str] = None) -> Tuple[Tensor, Tensor]: ...
    def equal(self, y: Tensor, name: Optional[str] = None) -> Tensor: ...
    def equal_all(self, y: Tensor, name: Optional[str] = None) -> Tensor: ...
    def erf(self, name: Optional[str] = None) -> Tensor: ...
    def erfinv(self, name: Optional[str] = None) -> Tensor: ...
    def erfinv_(self, name: Optional[str] = None) -> None: ...
    def exp(self, name: Optional[str] = None) -> Tensor: ...
    def exp_(self, name: Optional[str] = None) -> None: ...
    def expand(self, shape, name: Optional[str] = None) -> Tensor: ...
    def expand_as(self, y: Tensor, name: Optional[str] = None) -> Tensor: ...
    def exponential_(self, lam=1.0, name: Optional[str] = None) -> Tensor: ...
    def fill_(self, value) -> None: ...
    def fill_diagonal_(self, value, offset=0, wrap=False, name: Optional[str] = None) -> None: ...
    def fill_diagonal_tensor(self, y: Tensor, offset=0, dim1=0, dim2=1, name: Optional[str] = None) -> Tensor: ...
    def fill_diagonal_tensor_(self, y: Tensor, offset=0, dim1=0, dim2=1, name: Optional[str] = None) -> None: ...
    def flatten(self, start_axis: int = 0, stop_axis: int = -1, name: Optional[str] = None) -> Tuple[Tensor, Tensor]: ...
    def flatten_(self, start_axis: int = 0, stop_axis: int = -1, name: Optional[str] = None) -> None: ...
    def flip(self, axis, name: Optional[str] = None) -> Tensor: ...
    def floor(self, name: Optional[str] = None) -> Tensor: ...
    def floor_(self, name: Optional[str] = None) -> None: ...
    def floor_divide(self, y: Tensor, name: Optional[str] = None) -> Tensor: ...
    def floor_mod(self, y: Tensor, name: Optional[str] = None) -> Tuple[]: ...
    def fmax(self, y: Tensor, name: Optional[str] = None) -> Tensor: ...
    def fmin(self, y: Tensor, name: Optional[str] = None) -> Tensor: ...
    def gather(self, index, axis: Optional[int] = None, name: Optional[str] = None) -> Tensor: ...
    def gather_nd(self, index, name: Optional[str] = None) -> Tensor: ...
    def gcd(self, y: Tensor, name: Optional[str] = None) -> Tuple[]: ...
    def gradient(self) -> Tuple[]: ...
    def greater_equal(self, y: Tensor, name: Optional[str] = None) -> Tensor: ...
    def greater_than(self, y: Tensor, name: Optional[str] = None) -> Tensor: ...
    def histogram(self, bins=100, min=0, max=0, name: Optional[str] = None) -> Tensor: ...
    def imag(self, name: Optional[str] = None) -> Tensor: ...
    def increment(self, value=1.0, name: Optional[str] = None) -> Tensor: ...
    def index_sample(self, index) -> Tensor: ...
    def index_select(self, index, axis: int = 0, name: Optional[str] = None) -> Tensor: ...
    def inner(self, y: Tensor, name: Optional[str] = None) -> Tuple[]: ...
    def inverse(self, name: Optional[str] = None) -> Tensor: ...
    def is_complex(self) -> bool: ...
    def is_empty(self, name: Optional[str] = None) -> Tensor: ...
    def is_floating_point(self) -> bool: ...
    def is_integer(self) -> bool: ...
    def is_tensor(self) -> bool: ...
    def isclose(self, y: Tensor, rtol=1e-05, atol=1e-08, equal_nan=False, name: Optional[str] = None) -> Tensor: ...
    def isfinite(self, name: Optional[str] = None) -> Tensor: ...
    def isinf(self, name: Optional[str] = None) -> Tensor: ...
    def isnan(self, name: Optional[str] = None) -> Tensor: ...
    def item(self, *args) -> Tuple[]: ...
    def kron(self, y: Tensor, name: Optional[str] = None) -> Tensor: ...
    def kthvalue(self, k, axis: Optional[int] = None, keepdim: bool = False, name: Optional[str] = None) -> Tuple[Tensor, Tensor]: ...
    def lcm(self, y: Tensor, name: Optional[str] = None) -> Tuple[]: ...
    def lerp(self, y: Tensor, weight, name: Optional[str] = None) -> Tensor: ...
    def lerp_(self, y: Tensor, weight, name: Optional[str] = None) -> None: ...
    def less_equal(self, y: Tensor, name: Optional[str] = None) -> Tensor: ...
    def less_than(self, y: Tensor, name: Optional[str] = None) -> Tensor: ...
    def lgamma(self, name: Optional[str] = None) -> Tensor: ...
    def log(self, name: Optional[str] = None) -> Tensor: ...
    def log10(self, name: Optional[str] = None) -> Tensor: ...
    def log1p(self, name: Optional[str] = None) -> Tensor: ...
    def log2(self, name: Optional[str] = None) -> Tensor: ...
    def logical_and(self, y: Tensor, out=None, name: Optional[str] = None) -> Tensor: ...
    def logical_not(self, out=None, name: Optional[str] = None) -> Tensor: ...
    def logical_or(self, y: Tensor, out=None, name: Optional[str] = None) -> Tensor: ...
    def logical_xor(self, y: Tensor, out=None, name: Optional[str] = None) -> Tensor: ...
    def logit(self, eps=None, name: Optional[str] = None) -> Tensor: ...
    def logsumexp(self, axis: Optional[int] = None, keepdim: bool = False, name: Optional[str] = None) -> Tensor: ...
    def lstsq(self, y: Tensor, rcond=None, driver=None, name: Optional[str] = None) -> Tuple[Tensor, Tensor, Tensor, Tensor]: ...
    def lu(self, pivot=True, get_infos=False, name: Optional[str] = None) -> Tuple[Tensor, Tensor, Tensor]: ...
    def lu_unpack(self, y: Tensor, unpack_ludata=True, unpack_pivots=True, name: Optional[str] = None) -> Tuple[Tensor, Tensor, Tensor]: ...
    def masked_select(self, mask, name: Optional[str] = None) -> Tensor: ...
    def matmul(self, y: Tensor, transpose_x=False, transpose_y=False, name: Optional[str] = None) -> Tensor: ...
    def matrix_power(self, n, name: Optional[str] = None) -> Tensor: ...
    def max(self, axis: Optional[int] = None, keepdim: bool = False, name: Optional[str] = None) -> Tensor: ...
    def maximum(self, y: Tensor, name: Optional[str] = None) -> Tensor: ...
    def mean(self, axis: Optional[int] = None, keepdim: bool = False, name: Optional[str] = None) -> Tensor: ...
    def median(self, axis: Optional[int] = None, keepdim: bool = False, name: Optional[str] = None) -> Tuple[]: ...
    def min(self, axis: Optional[int] = None, keepdim: bool = False, name: Optional[str] = None) -> Tensor: ...
    def minimum(self, y: Tensor, name: Optional[str] = None) -> Tensor: ...
    def mm(self, mat2, name: Optional[str] = None) -> Tuple[]: ...
    def mod(self, y: Tensor, name: Optional[str] = None) -> Tuple[]: ...
    def mode(self, axis: int = -1, keepdim: bool = False, name: Optional[str] = None) -> Tuple[Tensor, Tensor]: ...
    def moveaxis(self, source, destination, name: Optional[str] = None) -> Tuple[]: ...
    def multi_dot(self, name: Optional[str] = None) -> Tensor: ...
    def multiplex(self, index, name: Optional[str] = None) -> Tensor: ...
    def multiply(self, y: Tensor, name: Optional[str] = None) -> Tensor: ...
    def mv(self, vec, name: Optional[str] = None) -> Tensor: ...
    def nanmean(self, axis: Optional[int] = None, keepdim: bool = False, name: Optional[str] = None) -> Tuple[]: ...
    def nansum(self, axis: Optional[int] = None, dtype=None, keepdim: bool = False, name: Optional[str] = None) -> Tuple[]: ...
    def ndimension(self) -> Tuple[]: ...
    def neg(self, name: Optional[str] = None) -> Tuple[]: ...
    def nonzero(self, as_tuple=False) -> Tuple[]: ...
    def norm(self, p='fro', axis: Optional[int] = None, keepdim: bool = False, name: Optional[str] = None) -> Tuple[Tensor, Tensor]: ...
    def not_equal(self, y: Tensor, name: Optional[str] = None) -> Tensor: ...
    def numel(self, name: Optional[str] = None) -> Tuple[]: ...
    def outer(self, y: Tensor, name: Optional[str] = None) -> Tuple[]: ...
    def pow(self, y: Tensor, name: Optional[str] = None) -> Tensor: ...
    def prod(self, axis: Optional[int] = None, keepdim: bool = False, dtype=None, name: Optional[str] = None) -> Tuple[]: ...
    def put_along_axis(self, indices, values, axis, reduce='assign') -> Tensor: ...
    def put_along_axis_(self, indices, values, axis, reduce='assign') -> None: ...
    def qr(self, mode='reduced', name: Optional[str] = None) -> Tuple[Tensor, Tensor]: ...
    def quantile(self, q, axis: Optional[int] = None, keepdim: bool = False) -> Tuple[]: ...
    def rad2deg(self, name: Optional[str] = None) -> Tuple[]: ...
    def rank(self) -> Tuple[]: ...
    def real(self, name: Optional[str] = None) -> Tensor: ...
    def reciprocal(self, name: Optional[str] = None) -> Tensor: ...
    def reciprocal_(self, name: Optional[str] = None) -> None: ...
    def register_hook(self, hook) -> Tuple[]: ...
    def remainder(self, y: Tensor, name: Optional[str] = None) -> Tensor: ...
    def repeat_interleave(self, repeats, axis: Optional[int] = None, name: Optional[str] = None) -> Tensor: ...
    def reshape(self, shape, name: Optional[str] = None) -> Tuple[Tensor, Tensor]: ...
    def reshape_(self, shape, name: Optional[str] = None) -> None: ...
    def reverse(self, axis, name: Optional[str] = None) -> Tensor: ...
    def roll(self, shifts, axis: Optional[int] = None, name: Optional[str] = None) -> Tensor: ...
    def rot90(self, k=1, axes=[0, 1], name: Optional[str] = None) -> Tuple[]: ...
    def round(self, name: Optional[str] = None) -> Tensor: ...
    def round_(self, name: Optional[str] = None) -> None: ...
    def rsqrt(self, name: Optional[str] = None) -> Tensor: ...
    def rsqrt_(self, name: Optional[str] = None) -> None: ...
    def scale(self, scale=1.0, bias=0.0, bias_after_scale=True, act=None, name: Optional[str] = None) -> Tensor: ...
    def scale_(self, scale=1.0, bias=0.0, bias_after_scale=True, act=None, name: Optional[str] = None) -> None: ...
    def scatter(self, index, updates, overwrite=True, name: Optional[str] = None) -> Tensor: ...
    def scatter_(self, index, updates, overwrite=True, name: Optional[str] = None) -> None: ...
    def scatter_nd(self, updates, shape, name: Optional[str] = None) -> Tuple[]: ...
    def scatter_nd_add(self, index, updates, name: Optional[str] = None) -> Tensor: ...
    def set_value(self, value) -> Tuple[]: ...
    def shard_index(self, index_num, nshards, shard_id, ignore_value=-1) -> Tensor: ...
    def sign(self, name: Optional[str] = None) -> Tensor: ...
    def sin(self, name: Optional[str] = None) -> Tensor: ...
    def sinh(self, name: Optional[str] = None) -> Tensor: ...
    def slice(self, axes, starts, ends) -> Tensor: ...
    def solve(self, y: Tensor, name: Optional[str] = None) -> Tensor: ...
    def sort(self, axis: int = -1, descending=False, name: Optional[str] = None) -> Tuple[]: ...
    def split(self, num_or_sections, axis: int = 0, name: Optional[str] = None) -> List[Tensor]: ...
    def sqrt(self, name: Optional[str] = None) -> Tensor: ...
    def sqrt_(self, name: Optional[str] = None) -> None: ...
    def square(self, name: Optional[str] = None) -> Tensor: ...
    def squeeze(self, axis: Optional[int] = None, name: Optional[str] = None) -> Tuple[Tensor, Tensor]: ...
    def squeeze_(self, axis: Optional[int] = None, name: Optional[str] = None) -> None: ...
    def stack(self, axis: int = 0, name: Optional[str] = None) -> Tensor: ...
    def stanh(self, scale_a=0.67, scale_b=1.7159, name: Optional[str] = None) -> Tuple[]: ...
    def std(self, axis: Optional[int] = None, unbiased=True, keepdim: bool = False, name: Optional[str] = None) -> Tuple[]: ...
    def strided_slice(self, axes, starts, ends, strides, name: Optional[str] = None) -> Tensor: ...
    def subtract(self, y: Tensor, name: Optional[str] = None) -> Tensor: ...
    def subtract_(self, y: Tensor, name: Optional[str] = None) -> None: ...
    def sum(self, axis: Optional[int] = None, dtype=None, keepdim: bool = False, name: Optional[str] = None) -> Tensor: ...
    def t(self, name: Optional[str] = None) -> Tuple[]: ...
    def take_along_axis(self, indices, axis) -> Tensor: ...
    def tanh(self, name: Optional[str] = None) -> Tensor: ...
    def tanh_(self, name: Optional[str] = None) -> None: ...
    def tensordot(self, y: Tensor, axes=2, name: Optional[str] = None) -> Tuple[]: ...
    def tile(self, repeat_times, name: Optional[str] = None) -> Tensor: ...
    def to_dense(self) -> Tuple[]: ...
    def to_sparse_coo(self, sparse_dim) -> Tuple[]: ...
    def tolist(self) -> Tuple[]: ...
    def topk(self, k, axis: Optional[int] = None, largest=True, sorted=True, name: Optional[str] = None) -> Tuple[]: ...
    def trace(self, offset=0, axis1=0, axis2=1, name: Optional[str] = None) -> Tensor: ...
    def transpose(self, perm, name: Optional[str] = None) -> Tensor: ...
    def trunc(self, name: Optional[str] = None) -> Tensor: ...
    def unbind(self, axis: int = 0) -> List[Tensor]: ...
    def uniform_(self, min=-1.0, max=1.0, seed=0, name: Optional[str] = None) -> None: ...
    def unique(self, return_index=False, return_inverse=False, return_counts=False, axis: Optional[int] = None, dtype='int64', name: Optional[str] = None) -> Tuple[Tensor, Tensor, Tensor, Tensor]: ...
    def unique_consecutive(self, return_inverse=False, return_counts=False, axis: Optional[int] = None, dtype='int64', name: Optional[str] = None) -> Tuple[Tensor, Tensor, Tensor]: ...
    def unsqueeze(self, axis, name: Optional[str] = None) -> Tuple[Tensor, Tensor]: ...
    def unsqueeze_(self, axis, name: Optional[str] = None) -> None: ...
    def unstack(self, axis: int = 0, num=None) -> List[Tensor]: ...
    def values(self) -> Tuple[]: ...
    def var(self, axis: Optional[int] = None, unbiased=True, keepdim: bool = False, name: Optional[str] = None) -> Tuple[]: ...
    def where(self, x=None, y=None, name: Optional[str] = None) -> Tensor: ...
    def zero_(self) -> None: ...
